test-path C:\Windows\SysWOW64\msls31.dll
test-path C:\Windows\SysWOW64\Riched20.DLL
test-path C:\Windows\SysWOW64\iertutil.dll
test-path C:\Windows\SysWOW64\dxgi.dll
test-path C:\Windows\SysWOW64\d3d11.dll
test-path C:\Windows\SysWOW64\USP10.dll
test-path C:\Windows\system32\wow64cpu.dll
test-path C:\Windows\system32\wow64win.dll
test-path C:\Windows\system32\win32u.dll
test-path C:\Windows\SysWOW64\wintypes.dll
test-path C:\Windows\SysWOW64\efswrt.dll
test-path C:\Windows\SysWOW64\msxml6.dll
test-path C:\Windows\SysWOW64\VSSAPI.DLL
test-path C:\Windows\SysWOW64\SPP.dll
test-path C:\Windows\SysWOW64\PidGenX.dll
test-path C:\Windows\SysWOW64\d3d10warp.dll
test-path C:\Windows\SysWOW64\DWrite.dll
test-path C:\build\setups\en_office_professional_plus_2013_with_sp1_x86_dvd_3928181\setup.dll
test-path C:\Windows\SysWOW64\wer.dll
test-path C:\Windows\SysWOW64\VssTrace.DLL
test-path C:\Windows\SysWOW64\sxproxy.dll
test-path C:\Windows\SysWOW64\urlmon.dll
test-path C:\Windows\AppPatch\AcGenral.DLL
test-path C:\Windows\SysWOW64\SrClient.dll
test-path C:\Windows\SysWOW64\hhctrl.ocx
test-path C:\Windows\SysWOW64\edputil.dll
test-path C:\Windows\SysWOW64\hlink.dll
test-path C:\Windows\SysWOW64\cryptnet.dll
test-path C:\Windows\SysWOW64\gpapi.dll
test-path C:\Windows\SysWOW64\MPR.dll
test-path C:\Windows\SysWOW64\HID.DLL
test-path C:\Windows\SysWOW64\WINNSI.DLL
test-path C:\Windows\SysWOW64\MSACM32.dll
test-path C:\Windows\SysWOW64\rsaenh.dll
test-path C:\Windows\SysWOW64\samcli.dll
test-path C:\Windows\SysWOW64\dwmapi.dll
test-path C:\Windows\SysWOW64\WINMMBASE.dll
test-path C:\Windows\SysWOW64\OLEACC.dll
test-path C:\Windows\SysWOW64\WINSPOOL.DRV
test-path C:\Windows\SysWOW64\CRYPTSP.dll
test-path C:\Windows\SysWOW64\WINMM.dll
test-path C:\Windows\SysWOW64\apphelp.dll
test-path C:\Windows\SysWOW64\ntmarta.dll
test-path C:\Windows\SysWOW64\bcrypt.dll
test-path C:\Windows\SysWOW64\wininet.dll
test-path C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.14300.1061_none_c537bc984988ad88\Comctl32.dll
test-path C:\Windows\SysWOW64\UxTheme.dll
test-path C:\Windows\SysWOW64\msi.dll
test-path C:\Windows\SysWOW64\WTSAPI32.dll
test-path C:\Windows\SysWOW64\USERENV.dll
test-path C:\Windows\SysWOW64\IPHLPAPI.DLL
test-path C:\Windows\SysWOW64\win32u.dll
test-path C:\Windows\SysWOW64\VERSION.dll
test-path C:\Windows\SysWOW64\CRYPTBASE.dll
test-path C:\Windows\SysWOW64\SspiCli.dll
test-path C:\Windows\SysWOW64\combase.dll
test-path C:\Windows\SysWOW64\cfgmgr32.dll
test-path C:\Windows\SysWOW64\ole32.dll
test-path C:\Windows\SysWOW64\coml2.dll
test-path C:\Windows\SysWOW64\shcore.dll
test-path C:\Windows\SysWOW64\MSASN1.dll
test-path C:\Windows\SysWOW64\kernel.appcore.dll
test-path C:\Windows\SysWOW64\USER32.dll
test-path C:\Windows\SysWOW64\powrprof.dll
test-path C:\Windows\SysWOW64\ucrtbase.dll
test-path C:\Windows\SysWOW64\WS2_32.dll
test-path C:\Windows\SysWOW64\clbcatq.dll
test-path C:\Windows\SysWOW64\IMM32.DLL
test-path C:\Windows\SysWOW64\msvcp_win.dll
test-path C:\Windows\SysWOW64\SHELL32.dll
test-path C:\Windows\SysWOW64\GDI32.dll
test-path C:\Windows\SysWOW64\bcryptPrimitives.dll
test-path C:\Windows\SysWOW64\MSCTF.dll
test-path C:\Windows\SysWOW64\imagehlp.dll
test-path C:\Windows\SysWOW64\SHLWAPI.dll
test-path C:\Windows\SysWOW64\gdi32full.dll
test-path C:\Windows\SysWOW64\CRYPT32.dll
test-path C:\Windows\SysWOW64\KERNELBASE.dll
test-path C:\Windows\SysWOW64\profapi.dll
test-path C:\Windows\SysWOW64\RPCRT4.dll
test-path C:\Windows\SysWOW64\sechost.dll
test-path C:\Windows\SysWOW64\OLEAUT32.dll
test-path C:\Windows\SysWOW64\msvcrt.dll
test-path C:\Windows\SysWOW64\WINTRUST.dll
test-path C:\Windows\SysWOW64\windows.storage.dll
test-path C:\Windows\SysWOW64\advapi32.dll
test-path C:\Windows\SysWOW64\NSI.dll
test-path C:\Windows\SysWOW64\ntdll.dll
test-path C:\Windows\SYSTEM32\ntdll.dll
